### ISSUE TITLE
在线体验是怎么部署的？

### ISSUE THREAD

**Issue by jackadam1981** [ZiuChen/SuperMarkdown#3]
在线体验是怎么部署的？

**Comment by ZiuChen** [comment]
Github Pages

**Comment by jackadam1981** [comment]
配置了 ssh-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}，actions也都正确完成，访问时空白

https://jackadam1981.github.io/SuperMarkdown/

**Comment by ZiuChen** [comment]
刚检查了一下，访问网站请求的目标 html 文件时的JS入口文件名是 index.ts，这说明你部署的并不是构建后的代码，而是开发时的代码，问题应该出在你的 Github Pages 的配置上：
每次push后触发的部署，应该从 gh-pages 分支部署，而不是从 main 分支部署，可以检查下你仓库内的 Github Pages 配置是否正确

**Comment by jackadam1981** [comment]
![image](https://github.com/ZiuChen/SuperMarkdown/assets/28656671/13b2bf1a-3853-4c30-a691-eed9fcf9543f)
尝试手动改分支运行，不支持。

**Comment by ZiuChen** [comment]
<img width="1119" alt="image" src="https://github.com/ZiuChen/SuperMarkdown/assets/64892985/486fa910-8cec-4dfb-861f-52cebee7f796">

**Comment by jackadam1981** [comment]
解决了，谢谢。
